/*
* Root Application Layout
PATH: src/app/layout.tsx
PURPOSE: Defines the global HTML shell for the entire Next.js application, wrapping all pages with shared UI and context providers.
SUMMARY: This component sets up the root <html> and <body> tags, enforcing a 'dark' theme and loading the 'Inter' font. Its most critical role is wrapping the entire application in the <ConfiguratorProvider>, making the configurator's global state (the "Smarter Brain") accessible to every component. It also renders the persistent <AppHeader> and the global <Toaster> for notifications.
RELATES TO OTHER FILES:
- This is the root of the React component tree.
- It imports and renders <ConfiguratorProvider> from 'src/context/ConfiguratorContext.tsx', which is the "heart" of the app's state management.
- It imports and renders <AppHeader> from 'src/components/header/app-header.tsx' as the main, persistent site header.
- It imports 'globals.css' to apply global styles (like Tailwind defaults and CSS variables) to the entire application.
IMPORTS:
- Metadata from 'next'
- ./globals.css from (local)
- Toaster from '@/components/global/toaster'
- AppHeader from '@/components/header/app-header'
- ConfiguratorProvider from '@/context/ConfiguratorContext'
*/

import type {Metadata} from 'next';
import './globals.css';
import { Toaster } from "@/components/global/toaster";
import { AppHeader } from '@/components/header/app-header';
import { ConfiguratorProvider } from '@/context/ConfiguratorContext';

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased flex flex-col min-h-screen">
        <ConfiguratorProvider>
          <AppHeader />
          <main className="flex-1 flex flex-col">{children}</main>
          <Toaster />
        </ConfiguratorProvider>
      </body>
    </html>
  );
}