/* *file-summary*
PATH: src/components/header/breadcrumb.tsx

PURPOSE: Renders the configuration progress as a visually clear breadcrumb trail.

SUMMARY: This is a **dumb UI component** that receives the current configuration steps as a string array (`history`) via props. It maps over this array to display the sequence of choices made by the user. It utilizes the `ChevronRight` icon as a separator between steps and applies distinct styling (e.g., `text-foreground`) to the final item in the array (the current step) to visually emphasize the user's current position in the flow.

RELATES TO OTHER FILES:
- It is imported and utilized by both 'src/components/header/app-header.tsx' (for mobile and desktop) and 'src/components/header/progress-tracker.tsx' (for the desktop view).
- It consumes the processed history array generated by 'src/components/header/app-header.tsx' from the `fullProductName` string derived from the configuration context.

IMPORTS:
- ChevronRight from 'lucide-react'

EXPORTS:
- Breadcrumb (React functional component)
*/


import { ChevronRight } from "lucide-react";

type BreadcrumbProps = {
  history: string[];
}

export function Breadcrumb({ history }: BreadcrumbProps) {
    return (
        <div className="flex items-center gap-1 text-xs sm:text-sm text-muted-foreground flex-wrap">
        {history.length > 0 &&
            history.map((item, index) => (
            <div key={index} className="flex items-center gap-1">
                {index > 0 && <ChevronRight className="w-4 h-4 text-gray-400" />}
                <span
                className={
                    index === history.length - 1
                    ? "font-medium text-foreground"
                    : ""
                }
                >
                {item}
                </span>
            </div>
            ))}
        </div>
    );
}
